name: sahibill
description: "SahiBill - bill and receipt auditor."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  cloud_firestore: ^6.10.0
  firebase_auth: ^6.7.0
  firebase_ai: ^4.0.0
  image_picker: ^1.2.4
  fl_chart: ^1.2.0
  google_fonts: ^8.2.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0F766E"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true