// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6CjOEpcc4A1o5LYASU6Wp9nTucYkbZE',
    appId: '1:219817292743:web:69d699f2446d4faafc1fe2',
    messagingSenderId: '219817292743',
    projectId: 'sahibill-46ec9',
    authDomain: 'sahibill-46ec9.firebaseapp.com',
    storageBucket: 'sahibill-46ec9.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBepGPdstBBlvwLSQNYs1qwb3AMmTXgnJQ',
    appId: '1:219817292743:android:9fee4cc7ae2c6396fc1fe2',
    messagingSenderId: '219817292743',
    projectId: 'sahibill-46ec9',
    storageBucket: 'sahibill-46ec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2TPfTUHEV9d8L7BJc5iqI_mv9CFMW1ro',
    appId: '1:219817292743:ios:ac8b8d8de95b5a85fc1fe2',
    messagingSenderId: '219817292743',
    projectId: 'sahibill-46ec9',
    storageBucket: 'sahibill-46ec9.firebasestorage.app',
    iosClientId: '219817292743-4tkafkilf7tu6lpniq3uv7aq3un7g5p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahibill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2TPfTUHEV9d8L7BJc5iqI_mv9CFMW1ro',
    appId: '1:219817292743:ios:ac8b8d8de95b5a85fc1fe2',
    messagingSenderId: '219817292743',
    projectId: 'sahibill-46ec9',
    storageBucket: 'sahibill-46ec9.firebasestorage.app',
    iosClientId: '219817292743-4tkafkilf7tu6lpniq3uv7aq3un7g5p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahibill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ6CjOEpcc4A1o5LYASU6Wp9nTucYkbZE',
    appId: '1:219817292743:web:170cb0311d6d4a7dfc1fe2',
    messagingSenderId: '219817292743',
    projectId: 'sahibill-46ec9',
    authDomain: 'sahibill-46ec9.firebaseapp.com',
    storageBucket: 'sahibill-46ec9.firebasestorage.app',
  );
}
